### ISSUE TITLE
0.8.15

### ISSUE THREAD

**Issue by mwittig** [josecastroleon/pimatic-openweather#20]
@sweetpi Can u please publish the new version? I don't have the access rights to publish it.

**Comment by PascalLaurens** [comment]
@mwittig How do you think about the arrayDay variable? I wrote the code as a fix for the weather forecast problem, but I regret the arrayDay variable part, because users have to change their config files now. "day": 1 means today now, instead of tomorrow. 

Do you think it's maybe wise to change that, before publishing it, so users don't have to change their config? If I'm right arrayday can just be replaced by day, so "day": 1 still means tomorrow.

**Comment by sweetpi** [comment]
Hi @mwittig published it and added you as a package owner, so you can publish it now directly.

**Comment by mwittig** [comment]
I am going to change this by setting the default for day to 2 which is the forcast for tomorrow. It is a braking change for users who set the day property and I'll make a note on this in the README. All other users perhaps didn't noticed they received the forcecast for the same day.

**Comment by mwittig** [comment]
Released with v0.9.0
